<?php

return [
    'brand' => [
        'name' => 'Bengal IT Hub',
        'company' => 'Bengal IT Hub Pvt. Ltd.',
        'tagline' => 'Future Ready Bengal',
        'phone' => '+91 9230653975',
        'email' => 'connect@bengalithub.com',
        'address' => '3rd Floor, Satavisha Bldg, 11 Hospital Link Road, Eastern Park, Santoshpur, Kolkata, India 700075.',
        'socials' => [
            'LinkedIn' => 'https://www.linkedin.com/company/bengal-it-hub',
            'Facebook' => 'https://www.facebook.com/profile.php?id=61585519843303',
            'Instagram' => 'https://www.instagram.com/bengalithub/',
            'X' => 'https://x.com/bengalithub',
            'YouTube' => 'https://www.youtube.com/@bengalithub',
        ],
    ],

    'nav' => [
        'Vision' => [
            'Vision 2030' => '/vision-2030',
            'About Us' => '/about-us',
        ],
        'Services' => [
            'Tech Ed/Fest' => '/tech-ed-fest',
            'Educamp' => '/educamp',
            'Eduverse' => '/eduverse-2',
            'Groomify' => '/groomify',
            'AI-Marketing' => '/ai-marketing',
            'Biz-Consultation' => '/biz-consultation',
            'Biz-Enablement' => '/biz-enablement',
            'E-Collab' => '/e-collab-2',
            'Staff Augmentation' => '/staff-augmentation',
            'Corporate Operations Outsourcing' => '/corporate-operations-outsourcing',
        ],
        'Products' => '/products',
        'Tech Talk' => [
            'TechBiz' => '/tech-biz',
            'Tech-Innovation' => 'https://test1.infoscience.co.in/',
        ],
        'Industries' => '/industries',
        'News & Events' => [
            'Hackfest Pragati 2026' => '/hackfest-2026',
            'Chief Guest' => '/hackfest-2026/chief-guest',
            'Chief Adviser' => '/hackfest-2026/chief-adviser',
            'Speakers & Panelists' => '/hackfest-2026/speakers',
            'FAQ' => '/hackfest-2026/faq',
            'Event Venue' => '/hackfest-2026/venue',
            'Register with Hackfest 2026' => '/hackfest-2026/register',
            'Partner With Us' => '/sponsor-hackfest-2026',
            'Sponsors Request Meeting' => '/sponsor-form-hackfest-2026',
        ],
        'Insights' => [
            'Blog' => '/blog',
            'Awards & Recognition' => '/awards-recognition',
        ],
        'Our Partners' => '/our-partners',
    ],

    'services' => [
        'tech-ed-fest' => [
            'title' => 'Tech Ed/Fest',
            'kicker' => 'Technology Comes Alive',
            'summary' => 'A high-impact industry enablement platform for technology seminars, leadership townhalls, corporate events, tech fests, and hackathons.',
            'body' => 'TechEd / TechFest is a dynamic industry-enablement platform designed to foster innovation, collaboration, and knowledge exchange. Through the strategic hosting of technology seminars, conferences, leadership townhalls, corporate events, tech fests, and hackathons. This initiative creates impactful ecosystems that connect academia, industry leaders, startups, professionals, and emerging talents.',
            'image' => 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '6+', 'label' => 'Event formats'],
                ['value' => '360°', 'label' => 'Ecosystem impact'],
                ['value' => '1', 'label' => 'Platform for talent and industry'],
            ],
            'features' => [
                'Technology seminars and expert knowledge sessions',
                'Industry conferences and leadership townhalls',
                'Corporate events, tech fests, and innovation showcases',
                'Hackathons that connect ideas with real-world problem solving',
                'Academic, startup, professional, and enterprise collaboration',
                'Networking formats for mentors, recruiters, founders, and talent',
            ],
            'formats' => [
                ['title' => 'Technology Seminars', 'body' => 'Focused expert sessions on AI, software, cloud, cybersecurity, product thinking, and emerging technology trends.', 'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Conferences', 'body' => 'Large-format knowledge platforms for thought leadership, networking, panel discussions, and industry visibility.', 'image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Leadership Townhalls', 'body' => 'Direct conversations between leaders, institutions, companies, founders, and professionals around future-ready growth.', 'image' => 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Corporate Events', 'body' => 'Brand-led experiences for employee engagement, product showcases, campus connect, hiring, and business networking.', 'image' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Tech Fests', 'body' => 'Campus and community festivals that combine learning, competitions, showcases, mentorship, and innovation culture.', 'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Hackathons', 'body' => 'Problem-solving programs where teams build prototypes, present solutions, and connect with mentors and recruiters.', 'image' => 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Plan the Theme', 'body' => 'Define event goals, audience, tracks, partners, speakers, and the outcome the program must create.'],
                ['step' => '02', 'title' => 'Curate the Ecosystem', 'body' => 'Bring together colleges, companies, startups, experts, mentors, recruiters, and communities.'],
                ['step' => '03', 'title' => 'Host the Experience', 'body' => 'Run the event with clear agenda, stage flow, branding, registration, sessions, and participant engagement.'],
                ['step' => '04', 'title' => 'Convert the Impact', 'body' => 'Turn participation into leads, hiring pipelines, collaborations, content, certificates, and future programs.'],
            ],
            'outcomes' => [
                'Stronger academia-industry bridge',
                'Better visibility for emerging talent',
                'Practical exposure to modern technology trends',
                'Startup, mentor, and investor interaction',
                'Corporate branding and recruitment access',
                'A repeatable platform for regional innovation',
            ],
            'audiences' => ['Students', 'Colleges', 'Startups', 'Industry Leaders', 'Corporate Teams', 'Technology Professionals'],
        ],
        'educamp' => [
            'title' => 'Educamp',
            'kicker' => 'Industry-Ready Learning Camps',
            'summary' => 'A flagship learning initiative designed to bridge the gap between academic knowledge and industry expectations through practical, mentor-led bootcamp training.',
            'body' => 'In a rapidly evolving digital world, the gap between academic knowledge and industry expectations continues to widen. Educamp, the flagship learning initiative of our IT Hub, is designed to bridge this gap with precision, innovation, and purpose.',
            'image' => 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '4+', 'label' => 'Bootcamp tracks'],
                ['value' => '100%', 'label' => 'Mentor-led delivery'],
                ['value' => '1', 'label' => 'Campus-to-corporate bridge'],
            ],
            'features' => [
                'Bootcamp-style learning tracks across in-demand technology domains',
                'Mentor-led practical exposure instead of theory-only learning',
                'Employability and digital capability building for every learner',
                'Live and simulated industry projects with real deliverables',
                'Career readiness coaching alongside technical skilling',
                'Structured progress tracking from foundation to placement-ready',
            ],
            'formats' => [
                ['title' => 'Technology Bootcamps', 'body' => 'Intensive, hands-on tracks in coding, cloud, data, and AI/ML foundations built around real project sprints.', 'image' => 'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Career Readiness Camps', 'body' => 'Resume building, interview preparation, workplace communication, and professional etiquette for a confident start.', 'image' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Industry Project Camps', 'body' => 'Live and simulated industry problem statements delivered under direct mentor supervision and feedback.', 'image' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Campus-to-Corporate Bridge', 'body' => 'Orientation on corporate culture, tools, and expectations so learners transition into the workplace with confidence.', 'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Assess the Gap', 'body' => 'Map the learner\'s current knowledge against real industry role expectations and identify the skill gap.'],
                ['step' => '02', 'title' => 'Design the Track', 'body' => 'Select the right bootcamp track, mentors, project briefs, and pace for the learner or cohort.'],
                ['step' => '03', 'title' => 'Run the Camp', 'body' => 'Deliver hands-on sessions, live projects, mentor check-ins, and career readiness coaching.'],
                ['step' => '04', 'title' => 'Certify and Connect', 'body' => 'Assess outcomes, issue certification, and connect learners to internship and hiring pathways.'],
            ],
            'outcomes' => [
                'Practical, job-relevant technical skills',
                'Confidence to work on real industry problems',
                'Stronger resumes and interview readiness',
                'Direct mentor feedback throughout the camp',
                'A verifiable certificate of completion',
                'A smoother path from campus to corporate roles',
            ],
            'audiences' => ['Students', 'Fresh Graduates', 'Career Switchers', 'Colleges', 'Training Partners', 'Hiring Companies'],
        ],
        'eduverse-2' => [
            'title' => 'Eduverse',
            'kicker' => 'Versatile Comprehensive Education with On-the-Job Training',
            'summary' => 'An integrated learning ecosystem combining academic knowledge with real-world, hands-on on-the-job training for industry-ready professionals.',
            'body' => 'Eduverse delivers an integrated learning ecosystem that combines academic knowledge with real-world, hands-on experience. Through structured on-the-job training, participants gain practical exposure while developing technical and professional capabilities aligned with industry standards. This approach creates job-ready professionals with both conceptual clarity and applied expertise.',
            'image' => 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '2-in-1', 'label' => 'Academic + on-the-job model'],
                ['value' => '100%', 'label' => 'Hands-on project exposure'],
                ['value' => '1', 'label' => 'Connected learning-to-career pathway'],
            ],
            'features' => [
                'Structured learning journeys blending theory with applied practice',
                'Real-world assignments mirroring live industry problem statements',
                'On-the-job training embedded directly into the curriculum',
                'Outcome-led technical and professional growth tracking',
                'Mentor-guided project delivery with continuous feedback',
                'Industry-aligned capability building for immediate role-readiness',
            ],
            'formats' => [
                ['title' => 'Foundation Learning Modules', 'body' => 'Core academic and conceptual grounding across the chosen technology or business domain.', 'image' => 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'On-the-Job Training Rotations', 'body' => 'Supervised placements inside live projects to apply classroom learning under real working conditions.', 'image' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Applied Capstone Projects', 'body' => 'End-to-end project ownership, from problem framing to delivery, testing, and final presentation.', 'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Professional Readiness Sprints', 'body' => 'Workplace communication, collaboration tools, and role-specific readiness coaching for a confident start.', 'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Build the Foundation', 'body' => 'Establish core conceptual knowledge across the chosen domain before any applied work begins.'],
                ['step' => '02', 'title' => 'Rotate On the Job', 'body' => 'Place learners inside supervised, real project environments to apply what they have learned.'],
                ['step' => '03', 'title' => 'Deliver a Capstone', 'body' => 'Own a complete project end-to-end, with mentor feedback and measurable delivery outcomes.'],
                ['step' => '04', 'title' => 'Graduate Role-Ready', 'body' => 'Exit with conceptual clarity, applied expertise, and a portfolio aligned to industry standards.'],
            ],
            'outcomes' => [
                'Conceptual clarity paired with applied expertise',
                'Direct, supervised exposure to real work environments',
                'A portfolio of completed, mentor-reviewed projects',
                'Technical and professional growth tracked to outcomes',
                'Faster, smoother transition from learning to employment',
                'Industry-aligned readiness from day one on the job',
            ],
            'audiences' => ['Students', 'Fresh Graduates', 'Colleges', 'Training Partners', 'Enterprise L&D Teams', 'Hiring Companies'],
        ],
        'groomify' => [
            'title' => 'Groomify',
            'kicker' => 'Shaping Industry-Ready Champions',
            'summary' => 'A professional grooming ecosystem that builds technical proficiency, communication skills, leadership qualities, and workplace adaptability.',
            'body' => 'Groomify focuses on holistic professional grooming to transform talent into high-performing industry contributors. The program enhances technical proficiency, communication skills, leadership qualities, and workplace adaptability, preparing individuals to excel as confident, future-ready professionals.',
            'image' => 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1531973576160-7125cd663d86?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '4', 'label' => 'Grooming pillars'],
                ['value' => '100%', 'label' => 'Practical, hands-on delivery'],
                ['value' => '1', 'label' => 'Confident industry-ready professional'],
            ],
            'features' => [
                'Technical proficiency training aligned to real industry tasks',
                'Communication and confidence-building workshops',
                'Leadership qualities developed through ownership-driven exercises',
                'Workplace adaptability across teams, tools, and expectations',
                'Before-and-after transformation tracking for every participant',
                'Confident, future-ready professionals ready to contribute from day one',
            ],
            'formats' => [
                ['title' => 'Technical Skill Labs', 'body' => 'Hands-on labs that sharpen core technical proficiency through real, task-based practice.', 'image' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Communication & Confidence Workshops', 'body' => 'Structured sessions that build clear, professional verbal and written communication.', 'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Leadership Simulation Camps', 'body' => 'Ownership-driven exercises that build decision-making and team-guiding leadership qualities.', 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Workplace Adaptability Drills', 'body' => 'Scenario-based practice that prepares participants for different teams, tools, and cultures.', 'image' => 'https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Assess the Talent', 'body' => 'Understand each participant\'s current technical, communication, and leadership baseline.'],
                ['step' => '02', 'title' => 'Groom the Pillars', 'body' => 'Run focused sessions across technical, communication, leadership, and adaptability tracks.'],
                ['step' => '03', 'title' => 'Simulate the Workplace', 'body' => 'Apply new capabilities under realistic, pressure-tested workplace scenarios.'],
                ['step' => '04', 'title' => 'Certify the Champion', 'body' => 'Confirm readiness and certify participants as confident, industry-ready professionals.'],
            ],
            'outcomes' => [
                'Confident, professional workplace communication',
                'Sound leadership and decision-making instincts',
                'Technical proficiency proven under real conditions',
                'Adaptability across teams, tools, and cultures',
                'A visible before-and-after professional transformation',
                'Readiness to contribute from day one on the job',
            ],
            'audiences' => ['Students', 'Fresh Graduates', 'Career Switchers', 'Colleges', 'Corporate Trainees', 'Hiring Companies'],
        ],
        'ai-marketing' => [
            'title' => 'AI-Marketing',
            'kicker' => 'Empowering Businesses with Cutting-Edge AI',
            'summary' => 'AI-powered marketing programs that turn data into measurable growth through customer insights, automation, and targeted campaigns.',
            'body' => 'AI Marketing leverages advanced artificial intelligence technologies to drive measurable business growth. From data-driven insights and customer behavior analytics to intelligent automation and targeted campaigns, this service enables organizations across diverse sectors to enhance brand visibility, optimize marketing ROI, and accelerate digital transformation.',
            'image' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '4', 'label' => 'AI marketing pillars'],
                ['value' => '24/7', 'label' => 'Automated campaign intelligence'],
                ['value' => '1', 'label' => 'Data-backed growth engine'],
            ],
            'features' => [
                'Customer behavior analytics that uncover real buying signals',
                'Campaign intelligence and automation across channels',
                'Targeted, personalized campaigns matched to audience intent',
                'Brand visibility optimization across digital touchpoints',
                'Marketing ROI tracking tied to measurable business outcomes',
                'Accelerated digital transformation for marketing operations',
            ],
            'formats' => [
                ['title' => 'Customer Behavior Analytics', 'body' => 'Deep analysis of customer data to uncover patterns, preferences, and buying signals.', 'image' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Campaign Intelligence & Automation', 'body' => 'AI-driven workflows that plan, launch, and optimize campaigns with minimal manual effort.', 'image' => 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Targeted & Personalized Campaigns', 'body' => 'Precision targeting that matches the right message to the right audience at the right time.', 'image' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'ROI & Growth Optimization', 'body' => 'Continuous performance tracking that reallocates spend toward what actually drives growth.', 'image' => 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Analyze the Data', 'body' => 'Study customer behavior, market signals, and existing campaign performance to find the real opportunity.'],
                ['step' => '02', 'title' => 'Design the Campaign', 'body' => 'Build AI-assisted targeting, messaging, and automation workflows around that opportunity.'],
                ['step' => '03', 'title' => 'Launch and Automate', 'body' => 'Run campaigns across channels with intelligent automation handling optimization in real time.'],
                ['step' => '04', 'title' => 'Measure and Scale', 'body' => 'Track ROI, double down on what works, and scale the growth engine across new segments.'],
            ],
            'outcomes' => [
                'Clearer visibility into customer behavior and intent',
                'Marketing workflows that run on intelligent automation',
                'Campaigns targeted with precision, not guesswork',
                'Stronger brand visibility across digital channels',
                'Marketing spend optimized toward measurable ROI',
                'A digital transformation partner for long-term growth',
            ],
            'audiences' => ['Startups', 'D2C Brands', 'Enterprises', 'Retail & E-Commerce', 'FinTech & Healthcare', 'Marketing Teams'],
        ],
        'biz-consultation' => [
            'title' => 'Biz-Consultation',
            'kicker' => 'Strategic Growth & Performance Enhancement',
            'summary' => 'Data-backed business advisory and operational guidance for efficiency, scalability, and profitability.',
            'body' => 'Our Business Consultation services provide strategic advisory and operational guidance to help organizations improve efficiency, scalability, and profitability. Through data-backed insights, process optimization, and growth planning, we enable businesses to strengthen their competitive positioning and achieve sustainable expansion.',
            'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '360°', 'label' => 'Business & market visibility'],
                ['value' => '100%', 'label' => 'Data-backed advisory'],
                ['value' => '1', 'label' => 'Growth and profitability partner'],
            ],
            'features' => [
                'Growth planning tied to clear, achievable milestones',
                'Process optimization that removes operational inefficiency',
                'Performance and market analysis grounded in real data',
                'Competitive positioning built for the actual market',
                'Profitability improvement through smarter resourcing',
                'Guidance for sustainable, long-term expansion',
            ],
            'formats' => [
                ['title' => 'Growth Planning', 'body' => 'Structured roadmaps that translate business goals into achievable growth milestones.', 'image' => 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Process Optimization', 'body' => 'Streamlining workflows and operations to remove inefficiency and unlock capacity.', 'image' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Performance & Market Analysis', 'body' => 'Data-backed evaluation of performance and market position to guide key decisions.', 'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Competitive Positioning', 'body' => 'Sharpening how the business stands out and competes within its market.', 'image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Diagnose the Business', 'body' => 'Assess current operations, performance data, and market position to find the real constraints.'],
                ['step' => '02', 'title' => 'Design the Strategy', 'body' => 'Build a growth plan with clear priorities, milestones, and resourcing.'],
                ['step' => '03', 'title' => 'Optimize the Operation', 'body' => 'Streamline processes and workflows to remove friction and unlock capacity.'],
                ['step' => '04', 'title' => 'Track and Scale', 'body' => 'Monitor performance against the plan and scale what is working.'],
            ],
            'outcomes' => [
                'A clearer growth roadmap tied to real business goals',
                'Leaner, more efficient operating processes',
                'Data-backed visibility into performance and market position',
                'Stronger competitive positioning in the market',
                'Higher profitability through smarter resource allocation',
                'A foundation for sustainable, long-term expansion',
            ],
            'audiences' => ['Startups', 'SMEs', 'Enterprises', 'Founders & CXOs', 'Operations Teams', 'Growth Teams'],
        ],
        'biz-enablement' => [
            'title' => 'Biz-Enablement',
            'kicker' => 'From Vision to Execution',
            'summary' => 'End-to-end support for launching, structuring, and scaling new ventures from idea to execution.',
            'body' => 'Business Enablement supports entrepreneurs and organizations in launching and structuring new ventures. From ideation validation and operational setup to compliance and go-to-market strategy, we provide end-to-end assistance to transform business concepts into successful enterprises.',
            'image' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => '4', 'label' => 'Venture-building stages'],
                ['value' => 'End-to-End', 'label' => 'Idea-to-execution support'],
                ['value' => '1', 'label' => 'Launch-ready enterprise'],
            ],
            'features' => [
                'Ideation and validation against real market demand',
                'Operational setup covering systems, teams, and workflows',
                'Compliance and governance foundations built in from day one',
                'Go-to-market strategy for a confident, credible launch',
                'End-to-end assistance from concept through execution',
                'A structured path from business idea to functioning enterprise',
            ],
            'formats' => [
                ['title' => 'Ideation & Validation', 'body' => 'Testing business concepts against real market demand before committing resources.', 'image' => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Operational Setup', 'body' => 'Structuring the systems, teams, and workflows a new venture needs to run.', 'image' => 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Compliance & Governance', 'body' => 'Establishing the legal, regulatory, and governance foundation for a credible business.', 'image' => 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Go-to-Market Strategy', 'body' => 'Planning the launch, positioning, and channels that get the business in front of customers.', 'image' => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Validate the Idea', 'body' => 'Test the business concept against real market demand and refine the value proposition.'],
                ['step' => '02', 'title' => 'Structure the Venture', 'body' => 'Set up the operations, teams, and workflows the business needs to function.'],
                ['step' => '03', 'title' => 'Establish Compliance', 'body' => 'Put the legal, regulatory, and governance foundation in place.'],
                ['step' => '04', 'title' => 'Launch to Market', 'body' => 'Execute a go-to-market plan that gets the business in front of real customers.'],
            ],
            'outcomes' => [
                'A validated business concept grounded in real demand',
                'Operational systems built to actually run the venture',
                'Legal and regulatory compliance from day one',
                'A clear go-to-market plan and launch strategy',
                'Faster time from idea to functioning enterprise',
                'A stronger foundation for scaling what works',
            ],
            'audiences' => ['Entrepreneurs', 'Startups', 'New Business Units', 'SMEs', 'Founders', 'Corporate Innovation Teams'],
        ],
        'e-collab-2' => [
            'title' => 'E-Collab',
            'kicker' => 'Consortium-Based Delivery Excellence',
            'summary' => 'A strategic collaboration model bringing complementary capabilities together for large-scale delivery and market expansion.',
            'body' => 'E-Collaboration fosters strategic partnerships by bringing together complementary capabilities under a consortium model. This collaborative ecosystem allows organizations to jointly deliver comprehensive solutions, expand market reach, and execute large-scale projects with agility and shared expertise.',
            'image' => 'https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => 'Multi-Partner', 'label' => 'Consortium delivery model'],
                ['value' => '100%', 'label' => 'Shared expertise approach'],
                ['value' => '1', 'label' => 'Unified delivery ecosystem'],
            ],
            'features' => [
                'Consortium model bringing complementary capabilities together',
                'Joint delivery of comprehensive, large-scale solutions',
                'Expanded market reach through combined partner networks',
                'Shared expertise that reduces individual delivery risk',
                'Agility and speed across multi-partner execution',
                'A repeatable framework for future collaborative ventures',
            ],
            'formats' => [
                ['title' => 'Startup Collaboration', 'body' => 'Partnering with startups to combine agility and innovation with delivery scale.', 'image' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Corporate Collaboration', 'body' => 'Joining forces with established organizations for complementary strength and reach.', 'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Consortium Delivery', 'body' => 'Multiple partners aligned under one model to execute large-scale projects together.', 'image' => 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Shared Expertise Programs', 'body' => 'Pooling specialized skills and capabilities so no single partner has to do it alone.', 'image' => 'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Map the Capabilities', 'body' => 'Identify complementary strengths across potential partners for the project at hand.'],
                ['step' => '02', 'title' => 'Form the Consortium', 'body' => 'Bring the right combination of partners together under one delivery model.'],
                ['step' => '03', 'title' => 'Deliver Jointly', 'body' => 'Execute the large-scale project with shared expertise, shared risk, and aligned roles.'],
                ['step' => '04', 'title' => 'Expand the Reach', 'body' => 'Use the consortium\'s combined market presence to reach further than any partner alone.'],
            ],
            'outcomes' => [
                'Access to complementary capabilities beyond one organization',
                'Faster delivery on large-scale, complex projects',
                'Expanded market reach through combined partner networks',
                'Shared expertise that reduces individual delivery risk',
                'The agility of a startup with the scale of an enterprise',
                'A repeatable model for future joint ventures',
            ],
            'audiences' => ['Startups', 'Enterprises', 'Government Bodies', 'Academic Institutions', 'Consortium Partners', 'Large-Scale Project Owners'],
        ],
        'staff-augmentation' => [
            'title' => 'Staff Augmentation',
            'kicker' => 'Future-Ready Workforce Solutions',
            'summary' => 'Flexible access to skilled, technology-enabled professionals who integrate into client teams and accelerate execution.',
            'body' => 'Our Staff Augmentation services provide skilled, technology-enabled professionals who seamlessly integrate into client teams. Designed to meet dynamic workforce demands, this model ensures flexibility, scalability, and access to specialized talent aligned with evolving industry requirements.',
            'image' => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => 'On-Demand', 'label' => 'Talent availability'],
                ['value' => '100%', 'label' => 'Role-fit professionals'],
                ['value' => '1', 'label' => 'Scalable workforce model'],
            ],
            'features' => [
                'On-demand talent pools of technology-enabled professionals',
                'Role-fit placements matched to real technical requirements',
                'Scalable team extension that flexes with project demand',
                'Seamless integration into existing client workflows',
                'Access to specialized talent aligned with industry needs',
                'A flexible workforce model built for changing priorities',
            ],
            'formats' => [
                ['title' => 'On-Demand Talent Pools', 'body' => 'Ready access to vetted, technology-enabled professionals when the need arises.', 'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Role-Fit Placements', 'body' => 'Matching specific technical roles to the right skill set, not just any available resource.', 'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Scalable Team Extension', 'body' => 'Scaling client teams up or down as project demands shift.', 'image' => 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Long-Term Embedded Talent', 'body' => 'Professionals who integrate deeply enough to work as a true extension of the client team.', 'image' => 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Understand the Need', 'body' => 'Define the exact role, skill set, and duration the client team requires.'],
                ['step' => '02', 'title' => 'Match the Talent', 'body' => 'Identify and vet technology-enabled professionals who fit the role precisely.'],
                ['step' => '03', 'title' => 'Integrate the Team', 'body' => 'Onboard the professional into the client\'s workflows, tools, and culture.'],
                ['step' => '04', 'title' => 'Scale as Needed', 'body' => 'Flex the team size up or down as the engagement and priorities evolve.'],
            ],
            'outcomes' => [
                'Faster access to specialized technical talent',
                'Teams that scale up or down with real demand',
                'Reduced hiring time and overhead for clients',
                'Professionals who integrate as true team members',
                'Continuity of skills across evolving project needs',
                'A flexible workforce model built for change',
            ],
            'audiences' => ['Enterprises', 'IT Companies', 'Startups', 'Product Teams', 'Project-Based Organizations', 'Hiring Managers'],
        ],
        'corporate-operations-outsourcing' => [
            'title' => 'Corporate Operations Outsourcing',
            'kicker' => 'Streamlining Administrative Excellence',
            'summary' => 'Back-office, compliance, and operations support that lets growing organizations focus on core business priorities.',
            'body' => 'Corporate Operations Outsourcing supports unorganized and growing business domains by managing essential administrative and operational functions. From back-office processes to corporate compliance and workflow management, we enable organizations to focus on core business priorities while ensuring operational efficiency and governance.',
            'image' => 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1500&q=90',
            'gallery' => [
                'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1100&q=88',
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1100&q=88',
            ],
            'stats' => [
                ['value' => 'End-to-End', 'label' => 'Back-office management'],
                ['value' => '100%', 'label' => 'Governance-aligned delivery'],
                ['value' => '1', 'label' => 'Operations partner for growth'],
            ],
            'features' => [
                'Back-office process management for routine administrative work',
                'Corporate compliance handled with consistency and accuracy',
                'Workflow and documentation management for smoother operations',
                'Operational efficiency programs that reduce cost and overhead',
                'Support built for unorganized and fast-growing business domains',
                'Governance that scales alongside the organization',
            ],
            'formats' => [
                ['title' => 'Back-Office Process Management', 'body' => 'Handling routine administrative and processing tasks so internal teams can focus elsewhere.', 'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Compliance & Governance Support', 'body' => 'Managing regulatory and governance requirements with consistency and accuracy.', 'image' => 'https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Workflow & Documentation Management', 'body' => 'Structuring day-to-day workflows and documentation for smoother operations.', 'image' => 'https://images.unsplash.com/photo-1503424886307-b090341d25d1?auto=format&fit=crop&w=900&q=88'],
                ['title' => 'Operational Efficiency Programs', 'body' => 'Ongoing process improvement that reduces cost and administrative overhead.', 'image' => 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=900&q=88'],
            ],
            'flow' => [
                ['step' => '01', 'title' => 'Assess Operations', 'body' => 'Review existing back-office processes, compliance gaps, and workflow bottlenecks.'],
                ['step' => '02', 'title' => 'Design the Outsourcing Model', 'body' => 'Define which functions move to a managed, outsourced operating model.'],
                ['step' => '03', 'title' => 'Manage the Function', 'body' => 'Run back-office, compliance, and workflow tasks with consistent governance.'],
                ['step' => '04', 'title' => 'Optimize Continuously', 'body' => 'Refine processes over time to reduce cost and improve operational efficiency.'],
            ],
            'outcomes' => [
                'Reduced administrative burden on internal teams',
                'Consistent compliance and governance across operations',
                'Streamlined back-office processes and documentation',
                'Lower operational costs through efficiency programs',
                'More internal focus on core business priorities',
                'A scalable operations model that grows with the business',
            ],
            'audiences' => ['Growing Businesses', 'SMEs', 'Startups', 'Enterprises', 'Operations Leaders', 'Compliance Teams'],
        ],
    ],

    'products' => [
        'intro' => [
            'eyebrow' => 'What We Build',
            'title' => 'Technology Products Built By Bengal IT Hub',
            'body' => [
                'Bengal IT Hub is a technology execution partner that designs, builds, and ships real software products, not just service engagements. We work across web, mobile, IoT, and AI, turning ideas from Eastern India into globally deployable products.',
                'Our teams build on a modern, production-tested stack: Laravel and PHP for robust backends, Vue and modern JavaScript for interactive interfaces, Tailwind CSS for fast and consistent design systems, MySQL and cloud-native infrastructure for reliable data and hosting, and applied AI and automation for intelligent, future-ready products.',
            ],
        ],
        'technologies' => ['Laravel & PHP', 'MERN Stack', 'Vue & JavaScript', 'Tailwind CSS', 'MySQL & Cloud Infrastructure', 'REST & GraphQL APIs', 'Generative & Agentic AI', 'IoT & Embedded Systems', 'DevOps & CI/CD'],
        'items' => [
            ['slug' => 'software-development', 'title' => 'Software Development', 'segment' => 'Software Development', 'summary' => 'Custom business software, CRM tools, admin panels, automation systems, SaaS platforms, and secure internal applications.', 'image' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'web-development', 'title' => 'Web Development', 'segment' => 'Web Development', 'summary' => 'Fast, responsive, SEO-ready websites, Laravel applications, company portals, landing pages, and high-converting digital experiences.', 'image' => 'https://images.unsplash.com/photo-1547658719-da2b51169166?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'app-development', 'title' => 'App Development', 'segment' => 'App Development', 'summary' => 'Mobile-first product planning, customer apps, business apps, dashboards, booking systems, and connected digital workflows.', 'image' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'iot-product-build', 'title' => 'IoT Product Build', 'segment' => 'IoT Product Build', 'summary' => 'Connected device concepts, sensor dashboards, monitoring systems, automation prototypes, and data-driven IoT product workflows.', 'image' => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'digital-marketing', 'title' => 'Digital Marketing', 'segment' => 'Digital Marketing', 'summary' => 'Performance marketing, SEO, social campaigns, brand content, analytics, lead generation, and AI-assisted growth strategy.', 'image' => 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'personal-product-build', 'title' => 'Personal Product Build', 'segment' => 'Personal Product Build', 'summary' => 'Founder MVPs, portfolio products, creator platforms, personal brand websites, learning products, and launch-ready prototypes.', 'image' => 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'generative-ai', 'title' => 'Generative AI', 'segment' => 'Generative AI', 'summary' => 'AI content tools, chat interfaces, workflow assistants, document automation, knowledge systems, and business AI integrations.', 'image' => 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=900&q=88', 'website' => null],
            ['slug' => 'agentic-ai', 'title' => 'Agentic AI', 'segment' => 'Agentic AI', 'summary' => 'AI agents that can plan, call tools, support operations, automate tasks, qualify leads, and assist teams with repeatable workflows.', 'image' => 'https://images.unsplash.com/photo-1526378722484-bd91ca387e72?auto=format&fit=crop&w=900&q=88', 'website' => null],
        ],
        'mission' => [
            'eyebrow' => 'Our Mission',
            'title' => "Building Products That Carry Bengal's Talent Onto A Global Stage",
            'body' => [
                "Every product we build is a chance to prove that world-class software can be designed and delivered from Eastern India. We combine deep technical craft with an understanding of real business problems, so what we ship isn't just functional, it's built to be used, trusted, and scaled.",
                'Our mission is to keep raising the bar on what a Bengal-built product looks like, from the first line of code to the partnerships, teams, and platforms that carry it into the world.',
            ],
            'images' => [
                ['src' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=88', 'alt' => 'Technology team collaborating on software development'],
                ['src' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=88', 'alt' => 'Business strategy discussion with technology partners'],
            ],
        ],
    ],

    'techbiz' => [
        'intro' => [
            'eyebrow' => 'Tech Talk',
            'title' => 'TechBiz',
            'body' => [
                "TechBiz is where Bengal IT Hub shares the technology conversations behind our work: partnership meetings, planning sessions, client discovery calls, and the internal reviews that shape how we build.",
                'It is a working record of how ideas move from a conversation in a room to a product, program, or partnership that reaches real people.',
            ],
        ],
        'categories' => [
            ['icon' => 'chat', 'title' => 'Meeting Highlights', 'body' => 'Recaps and takeaways from the conversations that shape our roadmap and delivery.'],
            ['icon' => 'partners', 'title' => 'Partnership Updates', 'body' => 'Academic, corporate, and community partnerships that extend what Bengal IT Hub can deliver.'],
            ['icon' => 'rocket', 'title' => 'Product & Tech Milestones', 'body' => 'Progress on the platforms, tools, and internal systems we are building or improving.'],
            ['icon' => 'globe', 'title' => 'Industry Collaboration', 'body' => 'Cross-sector conversations that connect our work to the wider technology ecosystem.'],
        ],
        'conversations' => [
            ['title' => 'Academic Partnership Discussions', 'tag' => 'Partnership Updates', 'body' => 'Working sessions with colleges and universities to align on curriculum, mentorship, and skilling opportunities.', 'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=88'],
            ['title' => 'AI & Automation Roadmap Reviews', 'tag' => 'Product & Tech Milestones', 'body' => 'Internal reviews of how AI and automation should shape our products and delivery over the next cycle.', 'image' => 'https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?auto=format&fit=crop&w=900&q=88'],
            ['title' => 'Hackathon & Innovation Planning', 'tag' => 'Meeting Highlights', 'body' => 'Planning sessions behind The Bengal HackFest PRAGATI 2026, from theme design to partner and venue coordination.', 'image' => 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=88'],
            ['title' => 'Client Kickoff & Discovery Sessions', 'tag' => 'Meeting Highlights', 'body' => 'First conversations with new clients to understand goals, constraints, and what a successful build looks like.', 'image' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=88'],
            ['title' => 'Cloud & Technology Vendor Syncs', 'tag' => 'Industry Collaboration', 'body' => 'Ongoing conversations with infrastructure and platform partners that keep our technology stack current and reliable.', 'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=88'],
            ['title' => 'Product Demos & Stakeholder Walkthroughs', 'tag' => 'Product & Tech Milestones', 'body' => 'Sessions where teams walk stakeholders through what has been built and gather feedback for the next iteration.', 'image' => 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&w=900&q=88'],
        ],
    ],

    'event' => [
        'name' => 'The Bengal HackFest PRAGATI 2026',
        'slug' => 'hackfest-2026',
        'badge' => "East India's Premier HackFest is Here",
        'tagline' => 'Where innovation meets opportunity. Students. Colleges. Corporates. One powerful ecosystem.',
        'venue' => 'Dr. T Sen Auditorium, Jadavpur University (Gate 3), Kolkata',
        'finale' => '20 April 2026',
        'counters' => ['Colleges' => '50+', 'Applicants' => '1000+', 'Teams in final round' => '250+', 'Cash Prize' => '1L+'],

        'timeline' => [
            ['Registration Opens', '16 Feb 2026', true],
            ['Nomination Deadline', '3 April (Friday)', false],
            ['Assignment Submission Deadline', '10 April (Friday)', false],
            ['Grand Finale', '20 April 2026', false],
        ],

        'people' => [
            ['Chief Guest', 'Dr. Mahuya Hom Choudhury', 'Dr. Mahuya Hom Choudhury is a senior IPR expert with 25+ years in innovation management, patent facilitation, and technology commercialization. As Senior Scientist and Nodal Officer for the Patent Information Centre and TISC at WBSCST (Dept. of Science & Technology & Biotechnology, West Bengal), she has led 1,000+ patentability assessments, facilitated 400+ filings, and helped secure 150+ granted patents. A registered patent and trademark attorney with an Integrated PhD in Biochemical Engineering, Dr. Choudhury has coordinated 60+ GI projects and received multiple national awards for strengthening West Bengal\'s IPR ecosystem.', ''],
            ['Chief Adviser', 'Mr. Debashis Sen', 'Debashis Sen is a seasoned public administrator and former IAS officer who served as Additional Chief Secretary (IT) and as MD/CMD for Smart City New Town for 15 years. An ENA (France) alumnus with executive training at Harvard Business School and the IMF Institute, he specializes in policy formulation, AI adoption advocacy, smart-city development, IT and startup policy, strategic planning, and urban governance.', 'https://www.linkedin.com/in/debashis-senias/'],
            ['Speakers & Panelists', 'Dr. Pallabi Sengupta', 'Dr. Pallabi Sengupta is an EdTech entrepreneur, academic leader, and founder-director of Human and Emotion Learning. An experienced HR and L&D professional with 12+ years in corporate roles, she is an international management coach with 50,000+ Udemy students and 100,000+ enrollments across 100 countries. Editor-in-chief of The Leader and HeProAI, acclaimed speaker and author of 25+ Bengali books, she holds degrees from Presidency College and Calcutta University, including a PhD in Human Resource Management.', ''],
            ['Speakers & Panelists', 'Dr. Swastik Nandi', 'Dr. Swastik Nandi is a consultant laparoscopic and laser surgeon at B.P. Poddar Hospital with over 20 years\' clinical experience. Trained at Calcutta Medical College, AIIMS New Delhi, and holding an international fellowship from the World Laparoscopy Hospital, he specializes in minimally invasive laparoscopic surgery and laser proctology. A frequent presenter at national and international conferences, Dr. Nandi is also a surgical lecturer and university examiner, and an active member of leading professional medical associations.', ''],
            ['Speakers & Panelists', 'Mr. Monoj K. Nath', 'Monoj K. Nath is Director and Creative Head at BlueAntz Advertising Pvt. Ltd. / Bluant Digital, with 32 years in advertising creative leadership. Former creative director at React, Lintas, O&M and Megaminds, he founded BlueAntz in 2012. An award-winning designer, Monoj has received consecutive Srijon Awards, the SOP Star Award for Packaging Design, and the All India Retail Jewellery Award; his agency has been recognized by Social Samosha and Silicon Magazine.', ''],
            ['Speakers & Panelists', 'Dr. Tanushyam Chattopadhyay', 'Dr. Tanushyam Chattopadhyay is Practice Head, Computer Vision at Sirius Digitech (Adani-International JV) with 23 years in AI. He leads product strategy, IP coordination, and university partnerships across the Adani Group, and has driven cross-functional teams to deploy computer vision and GenAI solutions. A PhD from Jadavpur University and MCA gold-medalist, he holds 100+ granted patents, ~70 publications, a book, and executive certifications in product and AI strategy, and serves on multiple academic boards.', 'https://www.linkedin.com/in/tanushyam-chattopadhyay-phd-in-computer-science-80291a11/'],
            ['Speakers & Panelists', 'Adv. Tapojit Dey', 'Tapojit Dey is a litigation and arbitration advocate with over 11 years\' practice at the Calcutta High Court. Formerly an empanelled counsel for Damodar Valley Corporation, he has represented prominent institutions including ISKCON across complex civil and commercial matters. Combining prior experience in human resources within the service industry with legal expertise, Tapojit brings practical organizational insight to dispute resolution, counsel, and courtroom strategy.', ''],
            ['Speakers & Panelists', 'Mr. Hemanta Ghosh', 'Hemanta Ghosh is an experienced engineering manager and technical architect with a strong track record in IT services. Skilled in Java/J2EE, Spring Boot, microservices, reactive programming, Vertex AI/LLMs, GCP Dataflow, Cassandra, Kafka, MongoDB, Docker, and observability tools (Kibana, Grafana), he excels in project delivery, people management, and agile practices. Hemanta holds an MBA from Carlson School of Management and combines deep technical expertise with strategic leadership to build scalable, production-ready systems.', ''],
            ['Speakers & Panelists', 'Dr. Ranjan Ghosh', 'Dr. Ranjan Ghosh is an adult and pediatric psychiatrist with 30+ years\' clinical experience and over 80,000 patients treated. Trained at Manipal Academy of Higher Education and UT Southwestern, he blends evidence-based care with psychoanalytic insight. Based in Kolkata, his specialties include bipolar disorder, PTSD, autism, anxiety and depression. Founder of Good Karma and creator of Karma AI, Dr. Ghosh champions mental health innovation, early access, and community-focused advocacy across India.', ''],
            ['Speakers & Panelists', 'Mr. Souvik Das', 'Souvik Das is a global AI and transformation leader at IBM, driving AI-led solutions and IBM Garage initiatives for large-scale business change. A three-time IBM Service Excellence Award winner, he previously led a 250+ consulting team at PwC India. Author of six books and a visiting faculty and mentor, Souvik judges national innovation programs and champions social impact initiatives for underprivileged children. Winner of the Kathasahitya Award, he blends technology, creativity, and purpose.', ''],
        ],

        'about' => [
            'eyebrow' => 'About The Bengal HackFest',
            'title' => 'What is PRAGATI 2026?',
            'intro' => 'The Bengal HackFest PRAGATI 2026 is a first-of-its-kind innovation platform in East India, designed to bring together:',
            'bullets' => ['Engineering & technology students', 'Academic institutions', 'Industry leaders & startups', 'Mentors, investors & ecosystem partners'],
            'closing' => 'This hackathon fosters real-world problem solving, innovation-driven collaboration, and industry-ready skills.',
        ],

        'participation' => [
            ['number' => '01.', 'title' => 'For Students:', 'bullets' => ['Work on real industry problem statements', 'Mentorship from experts', 'Internship & hiring opportunities', 'Certificates & recognition']],
            ['number' => '02.', 'title' => 'For Institutes:', 'bullets' => ['Strengthen NAAC/NIRF parameters', 'Showcase innovation culture', 'Faculty engagement opportunities', 'Academic branding at state level']],
            ['number' => '03.', 'title' => 'For Corporates:', 'bullets' => ['Access top tech talent', 'Brand visibility across East India', 'Recruitment pipeline building', 'Thought leadership positioning']],
        ],

        'sponsorship' => [
            'tiers' => ['Title Sponsor', 'Platinum Sponsor', 'Gold Sponsor'],
            'partnerTiers' => ['Innovation Partner', 'Hiring Partner'],
            'brochureUrl' => '/download-sponsor-brochure',
            'scheduleUrl' => '/contact',
        ],

        'whoShouldJoin' => [
            ['title' => 'Tech. Enthusiasts', 'description' => 'From Eastern India, if you are confident about your innovating capabilities.', 'tags' => ['MCA / B.Tech / M.Tech Students', 'AI / Data Science / IT Enthusiasts']],
            ['title' => 'Engineering Colleges', 'description' => null, 'tags' => ['AI / Data Science / Software Enthusiasts']],
        ],

        'whyMatters' => [
            'PRAGATI 2026 is more than a hackathon.',
            "It is a collaborative innovation platform designed to strengthen East India's digital ecosystem and bridge the gap between academia and industry.",
        ],

        'registerCtas' => [
            ['role' => 'As Contestant', 'description' => 'Solve real-world challenges, gain industry mentorship, boost skills, win recognition, and unlock career opportunities.', 'href' => '/hackfest-2026/register'],
            ['role' => 'As Academic Partner', 'description' => 'Build leadership skills for students, expand professional network, gain event experience, and collaborate with innovators and industry leaders.', 'href' => 'https://forms.gle/AQ6aC89YWZrJ93SL6'],
            ['role' => 'As Sponsor', 'description' => 'Gain brand visibility, access top talent, strengthen industry presence, and build strategic academic partnerships.', 'href' => 'https://forms.gle/AQ6aC89YWZrJ93SL6'],
        ],

        'venueDetails' => [
            'tags' => ['University Campus', 'Green Tech', 'Recognition'],
            'name' => 'Dr. Triguna Sen Auditorium',
            'campus' => 'Jadavpur University (Gate 3)',
            'address' => 'Kolkata 700032, India',
            'description' => 'A historic center of engineering excellence and innovation.',
        ],

        'supportersNote' => "We graciously thank our partners and collaborators as they're contributing to every measurable and immeasurable success of PRAGATI 2026. We welcome you to be one of them.",

        'faqs' => [
            ['What is The Bengal HackFest PRAGATI 2026?', 'The Bengal HackFest PRAGATI 2026 is a premier innovation-driven hackathon organized by The Bengal IT Hub, bringing together students, colleges, and corporates to solve real-world technology challenges. The Grand Finale will be held on 20 April 2026 at Jadavpur University Campus, Kolkata.'],
            ['Who can participate in Hackathon 2026?', 'Open to B.Tech / M.Tech students, engineering & IT students, AI / Data Science / Software enthusiasts, and final-year & pre-final year students. Participants need to join as teams (as per guidelines).'],
            ['Why should I join Hackathon?', 'This AI Hackathon, The Bengal HackFest PRAGATI 2026, offers real-world exposure, mentorship, networking, and over ₹1 Lakh in prizes. It helps students gain industry visibility and practical innovation experience within the hackathon India ecosystem.'],
            ['Is Hackathon online or in-person?', 'Hackathon 2026 is an in-person hackathon India event conducted at the Triguna Sen Auditorium inside Jadavpur University Campus, Kolkata. Participants must attend physically to collaborate, build, and present their projects live.'],
            ['Do I need coding experience to participate in Hackathon?', 'Basic technical knowledge is recommended. However, Hackathon HackFest PRAGATI 2026 encourages diverse teams, including designers, researchers, and strategists, not only coders.'],
            ['Is there a registration fee?', 'Details regarding the participation fee are mentioned in the registration section. Many hackathon activities and mentoring sessions may be free for registered participants.'],
            ['What will I build during the hackathon?', 'Participants will develop working prototypes or scalable technology solutions addressing real-world challenges under the AI Hackathon 2026 themes.'],
            ['What are the challenge themes in Hackathon?', 'Themes focus on AI-driven innovation, digital transformation, and scalable tech solutions aligned with industry needs or solutions that solve bigger supply-demand gaps in hackathon India initiatives.'],
            ['How do teams work in Hackathon?', 'Each team in this hackathon for students consists of five members collaborating intensively for one full day to ideate, develop, and present solutions.'],
            ['What tools or technologies can I use in Hackathon?', 'Participants in AI Hackathon 2026 may use any programming languages, frameworks, cloud tools, or AI technologies, provided they comply with event guidelines.'],
            ['How are the projects judged in Hackathon 2026?', 'Projects are evaluated by industry experts based on innovation, technical implementation, scalability, presentation, and real-world impact, ensuring transparency and EEAT compliance.'],
            ['What prizes can I win in Hackathon HackFest PRAGATI 2026?', 'Hackathon 2026 offers over ₹100000 (₹1 Lakh) in total prizes, along with special recognitions and certificates to top-performing teams.'],
            ['What do I need to submit in Hackathon?', 'Teams must submit a functional prototype, source code, and a presentation explaining the solution, innovation, and scalability aspects.'],
            ['What are the benefits for students?', 'Working on real industry problem statements, mentorship from experts, internship & hiring opportunities, certificates of participation / merit, and exposure to leading institutions and companies.'],
            ['What is the event format?', 'The event includes registration & shortlisting, a mentorship/development phase, final presentations, jury evaluation, and the Grand Finale & prize distribution on 20 April 2026. Detailed guidelines will be shared with registered participants.'],
            ['Will there be workshops or support during Hackathon HackFest PRAGATI 2026?', 'Yes. Mentors and technical experts will guide participants throughout this hackathon India event, offering support, feedback, and structured evaluation.'],
            ['Where will the final event be held?', "The Grand Finale will be hosted at the prestigious Jadavpur University Campus, Kolkata, one of Eastern India's most respected centers of engineering and innovation."],
            ['How can colleges become Academic Partners?', 'Colleges and Universities can participate as a Presenting Academic Partner, Gold Academic Partner, Silver Academic Partner, or Innovation / Department Partner. Academic Partners receive branding, faculty engagement opportunities, and recognition suitable for NAAC/NIRF documentation. For partnership discussions, please use the Academic Partnership section on the landing page.'],
            ['How can corporates sponsor the event?', 'Corporates can participate as a Title Sponsor, Gold Sponsor, Silver Sponsor, or Innovation / Hiring Partner. Sponsors gain brand visibility, recruitment access, and strategic engagement with top technical talent across East India.'],
            ['Will sponsors get access to participant resumes?', 'Yes. Corporate sponsors (as per sponsorship tier) will receive access to participant profiles and resumes (opt-in basis) for recruitment and internship opportunities.'],
            ['How can I stay updated?', 'You can register through the website, follow official announcements, subscribe for updates, or connect via email or phone mentioned on the contact section.'],
        ],
    ],

    'seo' => [
        'keywords' => 'Bengal IT Hub, AI Hackathon Kolkata, HackFest Pragati 2026, IT services Bengal, SaaS cloud solutions, staff augmentation, AI marketing',
        'robots' => 'index, follow',
    ],

    'faqs' => [
        ['What services do you offer?', 'We provide technology education, staff augmentation, AI marketing, business consultation, business enablement, collaboration, and corporate operations outsourcing.'],
        ['Can Bengal IT Hub support corporate hiring?', 'Yes. The staff augmentation and talent-readiness ecosystem is designed for flexible, enterprise-ready workforce support.'],
        ['How do I contact the team?', 'Use the contact form, call the published number, or connect through the listed social channels.'],
    ],
];
